std = "vim"

exclude = [
  "lua/fzfx/commons/*.lua",
  "lua/fzfx/commons/*/*.lua",
  "lua/fzfx/commons/*/*/*.lua",
]

[lints]
mixed_table = "allow"
unused_variable = "allow"
incorrect_standard_library_use = "allow"
global_usage = "allow"
if_same_then_else = "allow"

[config]
empty_if = { comments_count = true }
